# Uses [litsdoc](https://github.com/upvalue/litsdoc) with an alias to generate the HTML
# documentation
doc:
  ,litsdoc --argfile cfg/litsdoc.argfile

build:
  ./build.sh

# Start OpenOCD
debug-server:
  openocd -f interface/cmsis-dap.cfg -f target/rp2350.cfg

debug: 
  gdb -x cfg/gdb.init

flash:
  picotool load -u -v -x -t elf ./obj/main.elf

