#!/usr/bin/env python3
"""Embed a .scm file as a C header fragment: embed.py input.scm varname output.h"""
import os
import sys


def main():
    if len(sys.argv) != 4:
        sys.stderr.write("usage: embed.py input.scm varname output.h\n")
        return 1
    inp, var, out = sys.argv[1:4]
    with open(inp, "rb") as f:
        data = f.read()
    lines = ["/* generated by tools/embed.py from %s; do not edit */" % os.path.basename(inp)]
    lines.append("static const char %s[] = {" % var)
    for i in range(0, len(data), 16):
        # emit signed values so the char initializers never narrow
        vals = (b - 256 if b > 127 else b for b in data[i:i + 16])
        lines.append("  " + ", ".join(str(v) for v in vals) + ",")
    lines.append("};")
    lines.append("static const unsigned %s_len = %du;" % (var, len(data)))
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
