[build]
#target = "wasm32-unknown-unknown"
target = "riscv32imac-unknown-none-elf"



[target.riscv32imac-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "relocation-model=static",
]
