// state.c — State construction, unwind plumbing, signal-site handler walk.
#include "state.h"
#include "ns.h"
#include "eval.h"
#include "builtins.h"
#include "printer.h"
#include <stdarg.h>

#include "ot_expander_scm.h"  // generated by tools/embed.py (meson custom_target)
#include "ot_prelude_scm.h"

static u32 I(Intern* in, const char* s) { return intern_id(in, s, (u32)strlen(s)); }

static void init_syms(State* vm) {
  Intern* in = &vm->intern;
  Syms* S = &vm->syms;
#define OT_INIT_SYM(field, text) S->field = I(in, text);
  OT_SYM_LIST(OT_INIT_SYM)
#undef OT_INIT_SYM
}

// GC root walker: everything the State holds live values in.
static void state_walk_roots(void* ud, VisitFn visit, void* ctx) {
  State* vm = (State*)ud;
  for (u32 i = 0; i < vm->stack.len; i++) visit(ctx, &vm->stack.data[i]);
  visit(ctx, &vm->nsRegistry);
  visit(ctx, &vm->typeParents);
  visit(ctx, &vm->unwindCondition);
  visit(ctx, &vm->unwindRestartArgs);
  for (u32 i = 0; i < vm->handlers.len; i++) {
    visit(ctx, &vm->handlers.data[i].pred);
    visit(ctx, &vm->handlers.data[i].handler);
  }
  for (u32 i = 0; i < vm->restarts.len; i++) visit(ctx, &vm->restarts.data[i].restart);
  for (u32 i = 0; i < vm->paramBindings.len; i++) {
    visit(ctx, &vm->paramBindings.data[i].param);
    visit(ctx, &vm->paramBindings.data[i].value);
  }
  for (u32 i = 0; i < vm->frames.len; i++) visit(ctx, &vm->frames.data[i].fn);
}

// Evaluate one embedded bootstrap file; any read or eval error here is a
// build defect, so fail hard with the condition's printed form.
static void eval_embedded(State* vm, const char* name, const char* src, u32 len) {
  Value result = eval_source(vm, src, len, name);
  if (result.tag == Tag_Unwind) {
    Buf msg = {0};
    buf_printf(&msg, "bootstrap failed in %s: ", name);
    print_repr(vm, vm->unwindCondition, &msg);
    vec_push(&msg, '\0');
    ot_fatal(msg.data);
  }
}

State* state_create(const StateConfig* cfg) {
  StateConfig c = cfg ? *cfg : state_config_default();
  State* vm = ot_alloc(sizeof(State));
  memset(vm, 0, sizeof(State));
  vm->cfg = c;
  heap_init(&vm->heap, vm, c.heapBytes, c.heapMaxBytes);
  intern_init(&vm->intern);
  heap_add_roots(&vm->heap, state_walk_roots, vm);
  vm->nsRegistry = nil_v();
  vm->typeParents = nil_v();
  vm->currentNs = 0;
  vm->expandNs = 0;
  vm->gensymCounter = 0;
  vm->restartIdCounter = 0;
  vm->interruptFlag = false;
  vm->writeFn = nullptr;
  vm->writeUd = nullptr;
  vm->loadFn = nullptr;
  vm->loadUd = nullptr;
  vm->unwindKind = UnwindKind_None;
  vm->unwindCondition = nil_v();
  vm->unwindRestartId = 0;
  vm->unwindRestartArgs = nil_v();
  vm->handlerVisible = 0xffffffffu;

  init_syms(vm);
  vm->nsRegistry = make_table(vm);
  state_push(vm, vm->nsRegistry);  // stack[0]: permanent root
  vm->typeParents = make_table(vm);
  state_push(vm, vm->typeParents);  // stack[1]: permanent root

  vm->currentNs = vm->syms.otiumCore_;
  ns_get_or_create(vm, vm->syms.otiumCore_);
  register_cond(vm);
  register_expand(vm);
  register_arith(vm);
  register_time(vm);
  register_data(vm);
  register_string(vm);
  register_sys(vm);
  // The embedded bootstrap is required. Load it into otium.core before `user`
  // is created so the user's auto-refer snapshot includes its public bindings.
  eval_embedded(vm, "<expander.scm>", ot_expander_scm, ot_expander_scm_len);
  eval_embedded(vm, "<prelude.scm>", ot_prelude_scm, ot_prelude_scm_len);
  ns_get_or_create(vm, vm->syms.user_);
  vm->currentNs = vm->syms.user_;
  return vm;
}

void state_destroy(State* vm) {
  // Run extension finalizers while every State member is still alive. Heap is
  // the first member and is destroyed last; waiting for heap_deinit would
  // expose finalizers to an already-destroyed Intern, stack, and registries.
  heap_finalize_foreign_objects(&vm->heap);
  // Mirror the C++ member destruction order (reverse of declaration).
  vec_deinit(&vm->nativeModules);
  vec_deinit(&vm->frames);
  vec_deinit(&vm->loadingNs);
  vec_deinit(&vm->paramBindings);
  vec_deinit(&vm->restarts);
  vec_deinit(&vm->handlers);
  vec_deinit(&vm->stack);
  intern_deinit(&vm->intern);
  heap_deinit(&vm->heap);
  ot_free(vm);
}

void register_native_module(State* vm, const char* name, NativeModuleInit init) {
  u32 nameSym = intern_id(&vm->intern, name, (u32)strlen(name));
  for (u32 i = 0; i < vm->nativeModules.len; i++) {
    NativeModule* module = &vm->nativeModules.data[i];
    if (module->nameSym != nameSym) continue;
    if (module->init != init) ot_fatal("native module registered twice");
    return;
  }
  vec_push(&vm->nativeModules, ((NativeModule){nameSym, init, false}));
}

NativeModule* find_native_module(State* vm, u32 nameSym) {
  for (u32 i = 0; i < vm->nativeModules.len; i++)
    if (vm->nativeModules.data[i].nameSym == nameSym) return &vm->nativeModules.data[i];
  return nullptr;
}

Value state_push_handler(State* vm, Value pred, Value handler) {
  vec_push(&vm->handlers, ((HandlerBinding){pred, handler}));
  return nil_v();
}

void state_pop_handler(State* vm) {
  if (vm->handlers.len) (void)vec_pop(&vm->handlers);
}

void state_cancel_unwind(State* vm) {
  vm->unwindKind = UnwindKind_None;
  vm->unwindCondition = nil_v();
  vm->unwindRestartId = 0;
  vm->unwindRestartArgs = nil_v();
}

Value raise_error(State* vm, const char* fmt, ...) {
  char msg[512];
  va_list ap;
  va_start(ap, fmt);
  vsnprintf(msg, sizeof msg, fmt, ap);
  va_end(ap);
  u32 sc = scope_begin(vm);
  Slot c = scope_push(vm, make_table(vm));
  table_put(vm, slot_get(c), keyword_v(vm->syms.kwType), symbol_v(vm->syms.error_));
  {
    Value s = make_string(vm, msg, (u32)strlen(msg));  // may move the table
    table_put(vm, slot_get(c), keyword_v(vm->syms.kwMessage), s);
  }
  return scope_exit(vm, sc, signal_value(vm, slot_get(c), true));
}

Value raise_error_sym(State* vm, const char* fmt, u32 symId) {
  u32 len;
  const char* name = intern_name(&vm->intern, symId, &len);
  return raise_error(vm, fmt, (int)len, name);
}

Value signal_value(State* vm, Value c, bool unwindIfUnhandled) {
  u32 sc = scope_begin(vm);
  Slot croot = scope_push(vm, c);
  u32 limit = vm->handlerVisible < vm->handlers.len ? vm->handlerVisible : vm->handlers.len;
  for (u32 i = limit; i-- > 0;) {
    // read pred/handler through the handlers vector (a GC root) at each use:
    // a copy would go stale across the pred call's allocations
    Value t;
    {
      u32 s2 = scope_begin(vm);
      Slot b = scope_push(vm, slot_get(croot));
      t = apply(vm, vm->handlers.data[i].pred, b.idx, 1);
      scope_pop_to(vm, s2);
    }
    OT_TRYS(vm, sc, t);
    if (is_truthy(t)) {
      u32 savedVis = vm->handlerVisible;
      vm->handlerVisible = i;  // this binding + inner ones invisible
      Value hr;
      {
        u32 s2 = scope_begin(vm);
        Slot b2 = scope_push(vm, slot_get(croot));
        hr = apply(vm, vm->handlers.data[i].handler, b2.idx, 1);
        scope_pop_to(vm, s2);
      }
      vm->handlerVisible = savedVis;
      OT_TRYS(vm, sc, hr);
      // handler declined: continue outward
    }
  }
  if (unwindIfUnhandled) {
    vm->unwindKind = UnwindKind_Condition;
    vm->unwindCondition = slot_get(croot);
    return scope_exit(vm, sc, unwind_v());
  }
  return scope_exit(vm, sc, nil_v());
}
