# Uses [litsdoc](https://github.com/upvalue/litsdoc) with an alias to generate the HTML
# documentation
doc:
  ,litdocs

build:
  ./build.sh

# Start OpenOCD
debug-server:
  openocd -f interface/cmsis-dap.cfg -f target/rp2350.cfg

flash:
  picotool load -u -v -x -t elf ./blink.elf
