#!/usr/bin/env bash
# Run RISC-V kernel in QEMU
# This script reads configuration from the Meson build directory

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="${1:-$PROJECT_ROOT/build-riscv}"

# Check if build directory exists
if [ ! -d "$BUILD_DIR" ]; then
    echo "Error: Build directory not found: $BUILD_DIR"
    echo "Usage: $0 [build-directory]"
    echo "Example: $0 build-riscv"
    exit 1
fi

# Check if binary exists
KERNEL_ELF="$BUILD_DIR/os.elf"
if [ ! -f "$KERNEL_ELF" ]; then
    echo "Error: Kernel not found: $KERNEL_ELF"
    echo "Please build the kernel first with: meson compile -C $BUILD_DIR"
    exit 1
fi

# Source runtime configuration from Meson build directory
RUNTIME_CONFIG="$BUILD_DIR/runtime-config.sh"
if [ ! -f "$RUNTIME_CONFIG" ]; then
    echo "Error: Runtime configuration not found: $RUNTIME_CONFIG"
    echo "This file should be generated by Meson during setup."
    exit 1
fi

source "$RUNTIME_CONFIG"

# Configure display based on graphics backend
case "$RUNTIME_GRAPHICS_BACKEND" in
    OT_GRAPHICS_BACKEND_NONE)
        DISPLAY_ARGS="-display none"
        ;;
    OT_GRAPHICS_BACKEND_TEST)
        DISPLAY_ARGS="-display none"
        ;;
    OT_GRAPHICS_BACKEND_VIRTIO)
        # Use cocoa on macOS for graphical display
        if [[ "$OSTYPE" == "darwin"* ]]; then
            DISPLAY_ARGS="-device virtio-gpu-device -display cocoa"
        else
            # On Linux, use gtk or sdl
            DISPLAY_ARGS="-device virtio-gpu-device -display gtk"
        fi
        ;;
    *)
        echo "Warning: Unknown graphics backend: $RUNTIME_GRAPHICS_BACKEND"
        DISPLAY_ARGS="-display none"
        ;;
esac

# Start QEMU
echo "=== Running RISC-V kernel in QEMU ==="
echo "Kernel: $KERNEL_ELF"
echo "Graphics backend: $RUNTIME_GRAPHICS_BACKEND"
echo "Display args: $DISPLAY_ARGS"
echo ""

set -x 

exec qemu-system-riscv32 \
    -machine virt \
    -bios default \
    -drive id=drive0,file=test.txt,format=raw,if=none \
    -device virtio-blk-device,drive=drive0,bus=virtio-mmio-bus.0 \
    $DISPLAY_ARGS \
    -serial mon:stdio \
    --no-reboot \
    -kernel "$KERNEL_ELF"
