// state.cpp — State construction, unwind plumbing, signal-site handler walk.
#include "state.hpp"
#include "ns.hpp"
#include "eval.hpp"
#include "builtins.hpp"
#include "printer.hpp"
#include <cstdarg>

#include "ot_expander_scm.h"  // generated by tools/embed.py (meson custom_target)
#include "ot_prelude_scm.h"

namespace ot {

static u32 I(Intern& in, const char* s) { return in.intern(s, (u32)strlen(s)); }

static void init_syms(State& vm) {
  Intern& in = vm.intern;
  Syms& S = vm.syms;
  S.quote_ = I(in, "quote");
  S.if_ = I(in, "if");
  S.define_ = I(in, "define");
  S.def_ = I(in, "def");
  S.definePriv_ = I(in, "define-");
  S.setBang_ = I(in, "set!");
  S.lambda_ = I(in, "lambda");
  S.fn_ = I(in, "fn");
  S.defmacro_ = I(in, "defmacro");
  S.begin_ = I(in, "begin");
  S.do_ = I(in, "do");
  S.let_ = I(in, "let");
  S.while_ = I(in, "while");
  S.and_ = I(in, "and");
  S.or_ = I(in, "or");
  S.cond_ = I(in, "cond");
  S.else_ = I(in, "else");
  S.quasiquote_ = I(in, "quasiquote");
  S.unquote_ = I(in, "unquote");
  S.unquoteSplicing_ = I(in, "unquote-splicing");
  S.ns_ = I(in, "ns");
  S.inNs_ = I(in, "in-ns");
  S.require_ = I(in, "require");
  S.handlerBind_ = I(in, "handler-bind");
  S.restartCase_ = I(in, "restart-case");
  S.try_ = I(in, "try");
  S.catch_ = I(in, "catch");
  S.unwindProtect_ = I(in, "unwind-protect");
  S.defer_ = I(in, "defer");
  S.defparam_ = I(in, "defparam");
  S.withParams_ = I(in, "with-params");
  S.array_ = I(in, "array");
  S.table_ = I(in, "table");
  S.amp_ = I(in, "&");
  S.otiumCore_ = I(in, "otium.core");
  S.user_ = I(in, "user");
  S.expander_ = I(in, "*expander*");
  S.error_ = I(in, "error");
  S.quit_ = I(in, "quit");
  S.kwType = I(in, "type");
  S.kwMessage = I(in, "message");
  S.kwData = I(in, "data");
  S.kwName = I(in, "name");
  S.kwVars = I(in, "vars");
  S.kwAliases = I(in, "aliases");
  S.kwRefers = I(in, "refers");
  S.kwOrder = I(in, "order");
  S.kwAs = I(in, "as");
  S.kwRefer = I(in, "refer");
  S.kwReload = I(in, "reload");
  S.kwRequire = I(in, "require");
}

// GC root walker: everything the State holds live values in.
static void state_walk_roots(void* ud, Heap::VisitFn visit, void* ctx) {
  State* vm = (State*)ud;
  for (u32 i = 0; i < vm->stack.len; i++) visit(ctx, &vm->stack[i]);
  visit(ctx, &vm->nsRegistry);
  visit(ctx, &vm->typeParents);
  visit(ctx, &vm->unwindCondition);
  visit(ctx, &vm->unwindRestartArgs);
  for (u32 i = 0; i < vm->handlers.len; i++) {
    visit(ctx, &vm->handlers[i].pred);
    visit(ctx, &vm->handlers[i].handler);
  }
  for (u32 i = 0; i < vm->restarts.len; i++) visit(ctx, &vm->restarts[i].restart);
  for (u32 i = 0; i < vm->paramBindings.len; i++) {
    visit(ctx, &vm->paramBindings[i].param);
    visit(ctx, &vm->paramBindings[i].value);
  }
  for (u32 i = 0; i < vm->frames.len; i++) visit(ctx, &vm->frames[i].fn);
}

// Evaluate one embedded bootstrap file; any read or eval error here is a
// build defect, so fail hard with the condition's printed form.
static void eval_embedded(State& vm, const char* name, const char* src, u32 len) {
  Value result = eval_source(vm, src, len, name);
  if (result.tag == Tag::Unwind) {
    Buf msg;
    msg.printf("bootstrap failed in %s: ", name);
    print_repr(vm, vm.unwindCondition, msg);
    msg.push('\0');
    ot_fatal(msg.data);
  }
}

State::State(const StateConfig& c) : heap(this, c.heapBytes), intern(), stack(), cfg(c) {
  heap.addRoots(state_walk_roots, this);
  nsRegistry = nil_v();
  typeParents = nil_v();
  currentNs = 0;
  expandNs = 0;
  gensymCounter = 0;
  restartIdCounter = 0;
  depth = 0;
  interruptFlag = false;
  writeFn = nullptr;
  writeUd = nullptr;
  loadFn = nullptr;
  loadUd = nullptr;
  unwindKind = UnwindKind::None;
  unwindCondition = nil_v();
  unwindRestartId = 0;
  unwindRestartArgs = nil_v();
  handlerVisible = 0xffffffffu;

  init_syms(*this);
  nsRegistry = make_table(*this);
  push(nsRegistry);  // stack[0]: permanent root
  typeParents = make_table(*this);
  push(typeParents);  // stack[1]: permanent root

  currentNs = syms.otiumCore_;
  ns_get_or_create(*this, syms.otiumCore_);
  register_cond(*this);
  register_expand(*this);
  register_arith(*this);
  register_data(*this);
  register_string(*this);
  register_sys(*this);
  // The embedded bootstrap is required. Load it into otium.core before `user`
  // is created so the user's auto-refer snapshot includes its public bindings.
  eval_embedded(*this, "<expander.scm>", ot_expander_scm, ot_expander_scm_len);
  eval_embedded(*this, "<prelude.scm>", ot_prelude_scm, ot_prelude_scm_len);
  ns_get_or_create(*this, syms.user_);
  currentNs = syms.user_;
}

State* State::create(const StateConfig& cfg) { return new State(cfg); }
void State::destroy() { delete this; }

Value state_push_handler(State& vm, Value pred, Value handler) {
  vm.handlers.push(HandlerBinding{pred, handler});
  return nil_v();
}

void state_pop_handler(State& vm) {
  if (vm.handlers.len) vm.handlers.pop();
}

void state_cancel_unwind(State& vm) {
  vm.unwindKind = UnwindKind::None;
  vm.unwindCondition = nil_v();
  vm.unwindRestartId = 0;
  vm.unwindRestartArgs = nil_v();
}

Value raise_error(State& vm, const char* fmt, ...) {
  char msg[512];
  va_list ap;
  va_start(ap, fmt);
  vsnprintf(msg, sizeof msg, fmt, ap);
  va_end(ap);
  Scope sc(vm);
  Slot c = sc.push(make_table(vm));
  table_put(vm, c.get(), keyword_v(vm.syms.kwType), symbol_v(vm.syms.error_));
  {
    Value s = make_string(vm, msg, (u32)strlen(msg));  // may move the table
    table_put(vm, c.get(), keyword_v(vm.syms.kwMessage), s);
  }
  return signal_value(vm, c.get(), true);
}

Value raise_error_sym(State& vm, const char* fmt, u32 symId) {
  u32 len;
  const char* name = vm.intern.name(symId, &len);
  return raise_error(vm, fmt, (int)len, name);
}

Value signal_value(State& vm, Value c, bool unwindIfUnhandled) {
  Scope sc(vm);
  Slot croot = sc.push(c);
  u32 limit = vm.handlerVisible < vm.handlers.len ? vm.handlerVisible : vm.handlers.len;
  for (u32 i = limit; i-- > 0;) {
    // read pred/handler through the handlers vector (a GC root) at each use:
    // a copy would go stale across the pred call's allocations
    Value t;
    {
      Scope s2(vm);
      Slot b = s2.push(croot.get());
      t = apply(vm, vm.handlers[i].pred, b.idx, 1);
    }
    OT_TRY(t);
    if (is_truthy(t)) {
      u32 savedVis = vm.handlerVisible;
      vm.handlerVisible = i;  // this binding + inner ones invisible
      Value hr;
      {
        Scope s2(vm);
        Slot b2 = s2.push(croot.get());
        hr = apply(vm, vm.handlers[i].handler, b2.idx, 1);
      }
      vm.handlerVisible = savedVis;
      OT_TRY(hr);
      // handler declined: continue outward
    }
  }
  if (unwindIfUnhandled) {
    vm.unwindKind = UnwindKind::Condition;
    vm.unwindCondition = croot.get();
    return unwind_v();
  }
  return nil_v();
}

}  // namespace ot
