// vm.cpp — Vm construction, unwind plumbing, signal-site handler walk.
#include "vm.hpp"
#include "ns.hpp"
#include "eval.hpp"
#include "builtins.hpp"
#include "reader.hpp"
#include "printer.hpp"
#include <cstdarg>

#ifdef OT_EMBED_PRELUDE
#include "ot_expander_scm.h"  // generated by tools/embed.py (meson custom_target)
#include "ot_prelude_scm.h"
#endif

namespace ot {

static u32 I(Intern& in, const char* s) { return in.intern(s, (u32)strlen(s)); }

static void init_syms(Vm& vm) {
  Intern& in = vm.intern;
  Syms& S = vm.syms;
  S.quote_ = I(in, "quote");
  S.if_ = I(in, "if");
  S.define_ = I(in, "define");
  S.def_ = I(in, "def");
  S.definePriv_ = I(in, "define-");
  S.setBang_ = I(in, "set!");
  S.lambda_ = I(in, "lambda");
  S.fn_ = I(in, "fn");
  S.defmacro_ = I(in, "defmacro");
  S.begin_ = I(in, "begin");
  S.do_ = I(in, "do");
  S.let_ = I(in, "let");
  S.while_ = I(in, "while");
  S.and_ = I(in, "and");
  S.or_ = I(in, "or");
  S.cond_ = I(in, "cond");
  S.else_ = I(in, "else");
  S.quasiquote_ = I(in, "quasiquote");
  S.unquote_ = I(in, "unquote");
  S.unquoteSplicing_ = I(in, "unquote-splicing");
  S.ns_ = I(in, "ns");
  S.inNs_ = I(in, "in-ns");
  S.require_ = I(in, "require");
  S.handlerBind_ = I(in, "handler-bind");
  S.restartCase_ = I(in, "restart-case");
  S.try_ = I(in, "try");
  S.catch_ = I(in, "catch");
  S.unwindProtect_ = I(in, "unwind-protect");
  S.defer_ = I(in, "defer");
  S.defparam_ = I(in, "defparam");
  S.withParams_ = I(in, "with-params");
  S.array_ = I(in, "array");
  S.table_ = I(in, "table");
  S.amp_ = I(in, "&");
  S.otiumCore_ = I(in, "otium.core");
  S.user_ = I(in, "user");
  S.expander_ = I(in, "*expander*");
  S.error_ = I(in, "error");
  S.quit_ = I(in, "quit");
  S.kwType = I(in, "type");
  S.kwMessage = I(in, "message");
  S.kwData = I(in, "data");
  S.kwName = I(in, "name");
  S.kwVars = I(in, "vars");
  S.kwAliases = I(in, "aliases");
  S.kwRefers = I(in, "refers");
  S.kwOrder = I(in, "order");
  S.kwAs = I(in, "as");
  S.kwRefer = I(in, "refer");
  S.kwReload = I(in, "reload");
  S.kwRequire = I(in, "require");
}

// GC root walker: everything the Vm holds live values in.
static void vm_walk_roots(void* ud, Heap::VisitFn visit, void* ctx) {
  Vm* vm = (Vm*)ud;
  for (u32 i = 0; i < vm->stack.len; i++) visit(ctx, &vm->stack[i]);
  visit(ctx, &vm->nsRegistry);
  visit(ctx, &vm->typeParents);
  visit(ctx, &vm->unwindCondition);
  visit(ctx, &vm->unwindRestartArgs);
  for (u32 i = 0; i < vm->handlers.len; i++) {
    visit(ctx, &vm->handlers[i].pred);
    visit(ctx, &vm->handlers[i].handler);
  }
  for (u32 i = 0; i < vm->restarts.len; i++) visit(ctx, &vm->restarts[i].restart);
  for (u32 i = 0; i < vm->paramBindings.len; i++) {
    visit(ctx, &vm->paramBindings[i].param);
    visit(ctx, &vm->paramBindings[i].value);
  }
}

#ifdef OT_EMBED_PRELUDE
// Evaluate one embedded bootstrap file; any read or eval error here is a
// build defect, so fail hard with the condition's printed form.
static void eval_embedded(Vm& vm, const char* name, const char* src, u32 len) {
  Reader rd(vm, src, len, name);
  for (;;) {
    Value form = rd.next();
    if (form.tag != Tag::Unwind && rd.atEof()) break;
    Value r = form.tag == Tag::Unwind ? form : eval_form(vm, form);
    if (r.tag == Tag::Unwind) {
      Buf msg;
      msg.printf("bootstrap failed in %s: ", name);
      print_repr(vm, vm.unwindCondition, msg);
      msg.push('\0');
      ot_fatal(msg.data);
    }
  }
}
#endif

Vm::Vm(const VmConfig& c) : heap(this, c.heapBytes), intern(), stack(), cfg(c) {
  heap.addRoots(vm_walk_roots, this);
  nsRegistry = nil_v();
  typeParents = nil_v();
  currentNs = 0;
  expandNs = 0;
  gensymCounter = 0;
  restartIdCounter = 0;
  depth = 0;
  interruptFlag = false;
  writeFn = nullptr;
  writeUd = nullptr;
  loadFn = nullptr;
  loadUd = nullptr;
  unwindKind = UnwindKind::None;
  unwindCondition = nil_v();
  unwindRestartId = 0;
  unwindRestartArgs = nil_v();
  handlerVisible = 0xffffffffu;

  init_syms(*this);
  nsRegistry = make_table(*this);
  push(nsRegistry);  // stack[0]: permanent root
  typeParents = make_table(*this);
  push(typeParents);  // stack[1]: permanent root

  currentNs = syms.otiumCore_;
  ns_get_or_create(*this, syms.otiumCore_);
  register_eval_natives(*this);
  register_arith(*this);
  register_data(*this);
  register_string(*this);
  register_sys(*this);
#ifdef OT_EMBED_PRELUDE
  // Bootstrap into otium.core before `user` is created, so user's auto-refer
  // snapshot includes the prelude's publics.
  eval_embedded(*this, "<expander.scm>", ot_expander_scm, ot_expander_scm_len);
  eval_embedded(*this, "<prelude.scm>", ot_prelude_scm, ot_prelude_scm_len);
#endif
  ns_get_or_create(*this, syms.user_);
  currentNs = syms.user_;
}

Vm* Vm::create(const VmConfig& cfg) { return new Vm(cfg); }
void Vm::destroy() { delete this; }

Value vm_push_handler(Vm& vm, Value pred, Value handler) {
  vm.handlers.push(HandlerBinding{pred, handler});
  return nil_v();
}

void vm_pop_handler(Vm& vm) {
  if (vm.handlers.len) vm.handlers.pop();
}

void vm_cancel_unwind(Vm& vm) {
  vm.unwindKind = UnwindKind::None;
  vm.unwindCondition = nil_v();
  vm.unwindRestartId = 0;
  vm.unwindRestartArgs = nil_v();
}

Value raise_error(Vm& vm, const char* fmt, ...) {
  char msg[512];
  va_list ap;
  va_start(ap, fmt);
  vsnprintf(msg, sizeof msg, fmt, ap);
  va_end(ap);
  u32 root = vm.push(make_table(vm));
  table_put(vm, vm.stack[root], keyword_v(vm.syms.kwType), symbol_v(vm.syms.error_));
  {
    Value s = make_string(vm, msg, (u32)strlen(msg));  // may move the table
    table_put(vm, vm.stack[root], keyword_v(vm.syms.kwMessage), s);
  }
  Value r = signal_value(vm, vm.stack[root], true);
  vm.popTo(root);
  return r;
}

Value signal_value(Vm& vm, Value c, bool unwindIfUnhandled) {
  u32 croot = vm.push(c);
  u32 limit = vm.handlerVisible < vm.handlers.len ? vm.handlerVisible : vm.handlers.len;
  for (u32 i = limit; i-- > 0;) {
    // read pred/handler through the handlers vector (a GC root) at each use:
    // a copy would go stale across the pred call's allocations
    u32 b = vm.push(vm.stack[croot]);
    Value t = apply(vm, vm.handlers[i].pred, b, 1);
    vm.popTo(b);
    if (t.tag == Tag::Unwind) {
      vm.popTo(croot);
      return t;
    }
    if (is_truthy(t)) {
      u32 savedVis = vm.handlerVisible;
      vm.handlerVisible = i;  // this binding + inner ones invisible
      u32 b2 = vm.push(vm.stack[croot]);
      Value hr = apply(vm, vm.handlers[i].handler, b2, 1);
      vm.popTo(b2);
      vm.handlerVisible = savedVis;
      if (hr.tag == Tag::Unwind) {
        vm.popTo(croot);
        return hr;
      }
      // handler declined: continue outward
    }
  }
  Value cv = vm.stack[croot];
  vm.popTo(croot);
  if (unwindIfUnhandled) {
    vm.unwindKind = UnwindKind::Condition;
    vm.unwindCondition = cv;
    return unwind_v();
  }
  return nil_v();
}

}  // namespace ot
